### ISSUE TITLE
Automate testing of time series recipes

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/granite-timeseries-cookbook#12]

**Comment by adampingel** [comment]
To follow https://github.com/ibm-granite-community/granite-code-cookbook/issues/74

**Comment by adampingel** [comment]
Test are running, but only for the first notebook.  Add the other three.

**Comment by fayvor** [comment]
[PR here](https://github.com/ibm-granite-community/granite-timeseries-cookbook/pull/22). The tests pass, but take almost 1h.
